### ISSUE TITLE
file() versus just a straight string when importing SQL code into R

### ISSUE THREAD

**Issue by ellisp** [nz-social-investment-agency/social_housing#2]
In https://github.com/nz-social-investment-agency/social_housing/blob/master/rprogs/1.%20extract_dataset.R, for me

```R
app_data-query <- file("../sql/source_data_query.sql", "r")
```

leads to the subsequent call to `read_sql_table` not working (it sends an empty character string to the database).  Whereas the simpler

```R
app_data-query <- "../sql/source_data_query.sql"
```

Works fine.  So why not just use the simpler string?

**Comment by vinaybenny** [comment]
Cause: Unknown, as I'm unable to replicate the error. Wondering if differences in library version are causing the problem. 

Fix: Since Peter's suggestion of using the string works anyway, I'm replacing the line as per Peter's suggestion. Can be closed once the code is signed out.
